login:
  path: /login
  controller: App\Controller\SecurityController::login

home:
  path: /
  controller: App\Controller\HomeController::index

admin:
  path: /admin
  controller: App\Controller\AdminController::index
